# Generated by Django 3.1.7 on 2021-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaidaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehlel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
