# Generated by Django 3.1.7 on 2021-05-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NaidaApp', '0002_auto_20210504_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setgegdel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
    ]
